version: '3'

services:
    auth:
        image: gust4vossm/auth
        stdin_open: true
        tty: true
        networks:
            route-1:
                ipv4_address: 192.168.0.4
            route-2:
                ipv4_address: 192.168.1.4
            route-3:
                ipv4_address: 192.168.2.4
            route-4:
                ipv4_address: 192.168.3.4
            route-5:
                ipv4_address: 192.168.4.4
            route-6:
                ipv4_address: 192.168.5.4
    host-A:
        image: gust4vossm/hosts
        stdin_open: true
        tty: true
        environment:
            ID: 1
        networks:
            route-6:
                ipv4_address: 192.168.5.3
            route-1:
                ipv4_address: 192.168.0.2
    host-B:
        image: gust4vossm/hosts
        stdin_open: true
        tty: true
        environment:
            ID: 2
        networks:        
            route-1:
                ipv4_address: 192.168.0.3
            route-2:
                ipv4_address: 192.168.1.2
    host-C:
        image: gust4vossm/hosts
        stdin_open: true
        tty: true
        environment:
            ID: 3    
        networks:        
            route-2:
                ipv4_address: 192.168.1.3
            route-3:
                ipv4_address: 192.168.2.2             
    host-D:
        image: gust4vossm/hosts
        stdin_open: true
        tty: true
        environment:
            ID: 4
        networks:        
            route-3:
                ipv4_address: 192.168.2.3
            route-4:
                ipv4_address: 192.168.3.2             
    host-E:
        image: gust4vossm/hosts
        stdin_open: true
        tty: true
        environment:
            ID: 5
        networks:        
            route-4:
                ipv4_address: 192.168.3.3
            route-5:
                ipv4_address: 192.168.4.2                     
    host-F:
        image: gust4vossm/hosts
        stdin_open: true
        tty: true
        environment:
            ID: 6
        networks:        
            route-5:
                ipv4_address: 192.168.4.3
            route-6:
                ipv4_address: 192.168.5.2              

networks:
    route-1:
        ipam:
            config:
            -   subnet: 192.168.0.0/24
    route-2:
        ipam:
            config:
            -   subnet: 192.168.1.0/24
    route-3:
        ipam:
            config:
            -   subnet: 192.168.2.0/24
    route-4:
        ipam:
            config:
            -   subnet: 192.168.3.0/24
    route-5:
        ipam:
            config:
            -   subnet: 192.168.4.0/24
    route-6:
        ipam:
            config:
            -   subnet: 192.168.5.0/24
